services:

  openwakeword:
    container_name: openwakeword
    image: rhasspy/wyoming-openwakeword
    volumes:
      - ./config/openwakeword/custom:/custom
      - ./config/openwakeword/config:/config
    ports:
      - 10400:10400
      - 10400:10400/udp
    command: --preload-model 'ok_nabu' --custom-model-dir /custom
    restart: unless-stopped

  wyoming-piper-en:
    image: rhasspy/wyoming-piper
    container_name: piper
    restart: always
    ports:
      - 10200:10200
    volumes:
      - ./config/piper:/data
    command: --voice en_US-masterchief-medium

  wyoming-whisper-en:
    container_name: whisper
    image: lscr.io/linuxserver/faster-whisper:gpu
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WHISPER_MODEL=medium-int8
      - WHISPER_BEAM=5 #optional
      - WHISPER_LANG=en #optional
    volumes:
      - ./config/whisper:/data
    restart: always
    ports:
      - 10300:10300
    runtime: nvidia
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]